{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Ошибки"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "В Go ошибки воспринимаются как **одно из возможных** поведений программы, а не какое-то исключение.\n",
    "\n",
    "Функция, для которой возможен неудачный вызов, возвращает дополнительный результат, обычно последний в списке возвращаемых значений. Если неудача возможна только по одной причине, то возвращается булево значение как, например, при индексировании элемента в словаре. Если причин может быть несколько и необходимо объяснить почему возникла ошибка, то функция возвращает значение встроенного типа **error**.\n",
    "\n",
    "Тип error является **интерфейсным**. Что это значит и как влияет на обработку ошибок будет рассмотрено в главе 7, в которой изучаются интерфейсы. Пока достаточно знать, что значение типа error может быть равно **nil**, что означает отсутствие ошибок. Если error не равен nil, то есть ошибка и её описание можно получить вызовом метода **Error**. Обычно при возврате не nil значения, другие возвращаемые значения должны игнорироваться, но есть и исключения, когда функция может частично выполниться, как, например, при чтении из файла.\n",
    "\n",
    "Подход Go к обработке ошибок выделяется на фоне других языков программирования, в которых неудачный вызов передаётся через мезанизм исключений, а не обычных значений. Хотя в Go и есть своего рода исключения, они используются только при возникновении действительно неожиданных ошибок, которые точно указывают на баг, а не повседневных ошибок, которые хорошо написанная программа должна ожидать."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Go (lgo)",
   "language": "go",
   "name": "lgo"
  },
  "language_info": {
   "file_extension": "",
   "mimetype": "",
   "name": "go",
   "version": ""
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
